name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  smooth_page_indicator: ^1.2.0+3
  flutter_svg: ^2.0.10+1
  flutter_native_splash: ^2.4.1
  animated_splash_screen: ^1.3.0
  shimmer: ^3.0.0
  go_router: ^14.3.0
  sliding_clipped_nav_bar: ^3.1.1
  device_preview: ^1.2.0
  svg_flutter: ^0.0.1
  page_transition: ^2.1.0
  lottie: ^3.1.3
  timelines: ^0.1.0
  loading_animation_widget: ^1.3.0
  modal_progress_hud_nsn: ^0.5.1
  http: ^1.2.2
  fluttertoast: ^8.2.8
  another_flushbar: ^1.12.30
  provider: ^6.1.2
  html: ^0.15.4
  flutter_html: ^3.0.0-beta.2
  flutter_map: ^7.0.2
  geocode: ^1.0.3
  tuple: ^2.0.2
  latlong2: ^0.9.1
  positioned_tap_detector_2: ^1.0.4
  transparent_image: ^2.0.1
  proj4dart: ^2.1.0
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  get: ^4.6.6
  location: ^7.0.1
  geolocator: ^13.0.2
  http_parser: ^4.0.2
  path_provider: ^2.1.5
  flutter_background_service: ^5.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1



 
flutter_icons:
  image_path: "assets/logos/logoTwo.png" 
  android: true
  ios: true
  remove_alpha_ios: true 




# flutter_icons:
#   android: true
#   ios: true
#   image_path: "assets/logos/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/first_1.png
    - assets/images/second_2.png
    - assets/images/cal.png
    - assets/images/userprofile.png
    - assets/images/third_3.png
    - assets/logos/logo.png
    - assets/animations/
    - assets/gif/
